server:
  port: 8080
  servlet:
    context-path: /


spring:
  application:
    name: ecommerce

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:mem:appdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    data: classpath:data.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

